image:
  repository: ghcr.io/ziwon/gpu-scheduler
  tag: v0.1.0
  pullPolicy: IfNotPresent

webhook:
  image:
    repository: ghcr.io/ziwon/gpu-scheduler-webhook
    tag: v0.1.0
    pullPolicy: IfNotPresent
  caBundle: ""

agent:
  image:
    repository: ghcr.io/ziwon/gpu-scheduler-agent
    tag: v0.1.0
    pullPolicy: IfNotPresent

serviceAccountName: gpu-scheduler

crds:
  install: true
