apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-scheduler-config
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: gpu-scheduler
        plugins:
          preFilter:
            enabled:
              - name: GpuClaimPlugin
          filter:
            enabled:
              - name: GpuClaimPlugin
          score:
            enabled:
              - name: GpuClaimPlugin
          reserve:
            enabled:
              - name: GpuClaimPlugin
          preBind:
            enabled:
              - name: GpuClaimPlugin
