apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: gpu-scheduler-webhook
webhooks:
  - name: pods.gpu-scheduler.svc
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Ignore
    clientConfig:
      service:
        name: gpu-scheduler-webhook
        namespace: {{ .Release.Namespace }}
        path: /mutate
      {{- if .Values.webhook.caBundle }}
      caBundle: {{ .Values.webhook.caBundle }}
      {{- end }}
    {{- if or .Values.webhook.excludeNamespaces .Values.webhook.excludeOwnNamespace }}
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            {{- if .Values.webhook.excludeOwnNamespace }}
            - {{ .Release.Namespace }}
            {{- end }}
            {{- range .Values.webhook.excludeNamespaces }}
            - {{ . }}
            {{- end }}
    {{- end }}
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
